name: Build & Push (client)

on:
  push:
    branches: [ "main" ]
    paths:
      - 'client/**'
      - 'Dockerfile'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push client
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          target: client
          push: true
          tags: ghcr.io/${{ github.repository }}-client:latest
